print("hey there \nHow are you?")
print("hey there \nHow are you?\\newline")
print("hey there \tHow are you?")
print("hey there \tHow are you?\\t")
print("hey there \bHow are you?")
print("hey there \bHow are you?\\b")
print("hey there \rHow are you?")
print("hey there \rHow are you?\\r")
print("hey there \fHow are you?")
print("hey there \fHow are you?\\f")
print("hey there \vHow are you?")
print("hey there \vHow are you?\\v")
print("hey there \aHow are you?")
print("hey there \aHow are you?\\a")
print("hey there \\\\How are you?")
print("hey there \\'How are you?")
print("hey there \\\"How are you?") 
print("hey there \\How are you?")
print("hey there \'How are you?'\\n")
print("hey there \"How are you?\"\\n")
print("hey there \nHow are you?\\n")
print("hello World", "How are you", 5, 3.14, True, False)
print("Hellow World", "Kali", 5, sep=",", end="\n")
print("Hellow World", "Kali", 5, sep="//", end="\n")
print("Hellow World", "Kali", 5,end="::")
